version: '3.9'

services:
  nginx:
    container_name: ngo-nginx
    image: nginx:alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - nginx-opa
    depends_on:
      - opa
      - auth-service
      - first-service
      - second-service

  mongo:
    container_name: ngo-mongo
    image: mongo:latest
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ngo-mongo:/data/db
    networks:
      - nginx-opa

  auth-service:
    container_name: ngo-auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    networks:
      - nginx-opa
    depends_on:
      - mongo

  first-service:
    container_name: ngo-first-service
    build:
      context: ./service-1
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./service-1:/app
      - /app/node_modules
    networks:
      - nginx-opa

  second-service:
    container_name: ngo-second-service
    build:
      context: ./service-2
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    volumes:
      - ./service-2:/app
      - /app/node_modules
    networks:
      - nginx-opa

  opa:
    container_name: ngo-opa
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    volumes:
      - ./opa:/etc/opa
    environment:
      JWT_KEY: ${JWT_KEY}
    command:
      [
        "run",
        "--server",
        "--log-level=debug",
        "/etc/opa/auth.json",
        "/etc/opa/auth.rego"
      ]
    networks:
      - nginx-opa

networks:
  nginx-opa:
    name: nginx-opa
    driver: bridge

volumes:
  ngo-mongo:
    name: ngo-mongo
